#!/bin/sh
#
# sets up mountpoints neeeded after udev
#
set -e
start() {
    mount /mnt/data    
	echo "OK"
}
stop() {
    umount /mnt/data
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
