#!/bin/bash
export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export BUILDROOT_DIR=${SCRIPT_DIR}/../buildroot
export BASE_DIR=${BUILDROOT_DIR}/output
export HOST_DIR=${BASE_DIR}/host
export TARGET_DIR=${BASE_DIR}/target
export BUILD_DIR=${BASE_DIR}/build
export BINARIES_DIR=${BASE_DIR}/images
export STAGING_DIR=${BASE_DIR}/staging
